EntrantsApplication/EntrantsApplication.WebUI/Controllers/EntrantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Services;
using System.Web.Services;
using EntrantsApplication.Domain.Abstract;
using EntrantsApplication.Domain.Concrete;
using EntrantsApplication.Domain.Entities;
using EntrantsApplication.WebUI.Models.ApplicationModels;
using EntrantsApplication.WebUI.Models.ListView_Models;

namespace EntrantsApplication.WebUI.Controllers
{
    public class EntrantsController : Controller
    {
        IEntrantsRepository _entrantsRepository;
        ListViewEntrants _listViewEntrants = null;
      
        public EntrantsController()
        {                        
            _entrantsRepository = new EFEntrantsRepository();
            _listViewEntrants = new ListViewEntrants() { Entrants = _entrantsRepository.Entrants,
                Specialities = _entrantsRepository.Specialities };
        }

        public ActionResult MainMenu()
        {
            return View();
        }

        [HttpGet]
        public ViewResult AddEntrant()
        {
            return View();
        }

        [HttpPost]
        public ViewResult AddEntrant(Entrant entrant)
        {
            if (ModelState.IsValid)
            {
                _entrantsRepository.SaveEntrant(entrant);
                return View("AddingEntrantInformation", entrant);
            }
            else
                return View();
        }

        [HttpGet]
        public ViewResult AddApplication()
        {
            return View();
        }

        [HttpPost]
        public ViewResult AddApplication(EntrantApplication application)
        {
            if (ModelState.IsValid)
            {
                _entrantsRepository.SaveApplication(application);
                return View("MainMenu");
            }
            else
                return View();          
        }
         
        public JsonResult GetUniversitiesInfo(EntrantSpeciality[] model)
        {           
            if (model != null)
            {
                return Json(_entrantsRepository.getUniversitiesFromDatabase(model), JsonRequestBehavior.AllowGet);
            }
            return Json(_entrantsRepository.getUniversitiesFromDatabase(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetEducationFormsInfo(string[] model)
        {
            if (model.Length >= 1 && !model.Contains("Choose an option"))
            {
                if (model.Length == 1)
                    EFEntrantsRepository._currentEntrantsSpeciality = null;
                return Json(_entrantsRepository.getEducationFormsFromDatabase(model[0]), JsonRequestBehavior.AllowGet);
            }
            else
                return Json(null);
        }

        public JsonResult GetEducationPeriodsInfo(string[] model)
        {
            if (model.Length >= 2 && !model.Contains("Choose an option"))
                return Json(_entrantsRepository.getEducationPeriodsFromDatabase(model), JsonRequestBehavior.AllowGet);
            else
                return Json(null);
        }

        public JsonResult GetEducationFeesInfo(string[] model)
        {
            if (model.Length >= 3 && !model.Contains("Choose an option"))
                return Json(_entrantsRepository.getEducationFeesFromDatabase(model), JsonRequestBehavior.AllowGet);
            else
                return Json(null);
        }

        public JsonResult GetSpecialitiesInfo(string[] model)
        {
            if (model.Length >= 4 && !model.Contains("Choose an option"))
                return Json(_entrantsRepository.getSpecialitiesFromDatabase(model), JsonRequestBehavior.AllowGet);
            else
                return Json(null);
        }

        public JsonResult GetGroupSpecialitiesInfo(string[] model)
        {
            if (model.Length >= 5 && !model.Contains("Choose an option"))
            {
                if (model.Length == 5)
                    EFEntrantsRepository._currentEntrantsSpeciality = null;
                return Json(_entrantsRepository.getGroupSpecialities(model), JsonRequestBehavior.AllowGet);
            }
            else
                return Json(null);
        }

        public ViewResult WatchApplications()
        {
            var listApplications = new List<ListApplication>();
            var specialitiesDb = (new SpecialityDbContext()).Applications.ToArray();
            foreach (var application in specialitiesDb)
            {
                listApplications.Add(new ListApplication(application));
            }
            return View(listApplications);
        }
        
        [HttpGet]
        public ViewResult List(int? entrantId, Entrant deletedEntrant)
        {
            if (deletedEntrant.Name != null)
            {
                _entrantsRepository.SaveEntrant(deletedEntrant);
                return View(_listViewEntrants.getListViewEntrants());
            }
            else if (entrantId != null)
            {
                _listViewEntrants.getListViewEntrants().FirstOrDefault(x => x.EntrantId == entrantId).
                    SelectedEntrant = true;
            }
            return View(_listViewEntrants.getListViewEntrants());
        }

        [HttpPost]
        public JsonResult List(string[] model)
        {
            return Json(_listViewEntrants.getFilteredEntrants(model, _entrantsRepository), JsonRequestBehavior.AllowGet);
        }

        public ViewResult FullEntrantInformation(int entrantId)
        {
            var currentEntrant = _entrantsRepository.Entrants.FirstOrDefault(x => x.EntrantId == entrantId);
            return View(currentEntrant);
        }

        public ViewResult EditEntrant(int entrantId)
        {
            var currentEntrant = _entrantsRepository.Entrants.FirstOrDefault(x => x.EntrantId == entrantId);
            return View(currentEntrant);
        }

        public ViewResult EditEntrantInformation(Entrant entrant)
        {
            if (ModelState.IsValid)
            {
                _entrantsRepository.EditEntrant(entrant);
                return View("EdittingEntrantInformation", entrant);
            }
            else
                return View("EditEntrant", entrant);
        }

        public ViewResult DeleteEntrant(int entrantId)
        {
            var currentEntrant = _entrantsRepository.Entrants.FirstOrDefault(x => x.EntrantId == entrantId);
            _entrantsRepository.RemoveEntrant(currentEntrant);
            return View(currentEntrant);
        }
    }
}

EntrantsApplication/EntrantsApplication.WebUI/Views/Entrants/AddApplication.cshtml
@model EntrantsApplication.Domain.Entities.EntrantApplication

@{
    ViewBag.Title = "New Application";
}

<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/AddSpecialitiesInfo.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>

    <style>
        .speciality-div {
            background-color: lightblue;
            font-size: 20px;
            font-weight: 700;
            text-align: center;
            margin-bottom: 30px;
            padding-left: 40px;
            padding-right: 40px;
        }
    </style>
    <script>
        $(function () {
            $('#SpecialitiesContainer').sortable({
                items: '.sortable',
                stop: function (event, ui) {
                    var array = new Array();
                    array = ($.map($(this).find('div'), function (el) {
                        if (el.id != "")
                            return el.id + ' = ' + $(el).index();
                    }))
                    console.log(array);
                    getRightPriority(array);
                }
            });

        });
    </script>
</head>

<body onload="AddInfo(0)">
    <h2 style="text-align:center">Add Application</h2>
   
    <div style="margin-left:32px; margin-right:32px; text-align:justify">
        @using (Html.BeginForm())
        {
            <div id="HiddenElements">
                @Html.HiddenFor(x => Model.Speciality1Id, new { @id = "SpecialityId0" })
            </div>
            @Html.ValidationSummary()
            <div id="SpecialitiesContainer">
                <div id="0" class="speciality-div sortable">
                    <div>
                        <select style="margin-top: 10px; width: 100%" id="UniversitiesDropDown0"></select>
                    </div>
                    <div style="display:flex; justify-content:space-between">
                        <select style="width:33%" id="EducationFormsDropDown0"></select>
                        <select style="width:33%" id="EducationPeriodsDropDown0"></select>
                        <select style="width:33%" id="EducationFeesDropDown0"></select>
                    </div>
                    <div>
                        <select style="margin-bottom: 10px; width: 100%" id="SpecialitiesDropDown0"></select>
                    </div>
                </div>
               
            </div>

            <div style="text-align:center">
                <input class="btn-success" type="submit" value="Submit" />
            </div>
         }
    </div>
</body>

EntrantsApplication/EntrantsApplication.WebUI/Views/Entrants/AddingEntrantInformation.cshtml
@model EntrantsApplication.Domain.Entities.Entrant

@{
    ViewBag.Title = "Adding Entrant Information";
}

<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
</head>

<body>
    <div class="text-center">

        <h2>The entrant @Model.Name @Model.SecondName @Model.Surname was successfully added.</h2>
        @Html.ActionLink("Go back to Main Menu", "MainMenu")
        <p>
            @Html.ActionLink("Watch the List", "List")
        </p>
    </div>
</body>

EntrantsApplication/EntrantsApplication.WebUI/Views/Entrants/DeleteEntrant.cshtml
@model EntrantsApplication.Domain.Entities.Entrant

@{
    ViewBag.Title = "DeleteEntrant";
}
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
</head>

<body>
    <div class="text-center">
        <h2>The entrant by the name of @Model.Name @Model.SecondName @Model.Surname was successfully deleted.</h2>
        @Html.ActionLink("Go back to Main Menu", "MainMenu")
        <p>
            @Html.ActionLink("Go back to the List", "List")
            
        </p>
        <p>
            @Html.ActionLink("Restore Entrant", "List", Model)
        </p>
        
    </div>
</body>

EntrantsApplication/EntrantsApplication.WebUI/Views/Entrants/EditEntrant.cshtml
@model EntrantsApplication.Domain.Entities.Entrant

@{
    ViewBag.Title = "Editting an Entrant";
}

<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <script type="text/javascript" src="~/Scripts/SpecialityDropDowns.js"></script>

    <script>
        function AddChosenEntrantSpeciality() {
            $(document).ready(function () {
                $.getJSON(
                    '/jsonData/Faculties.json',
                    function (myObject) {
                        console.log(myObject);
                        var currentElement = document.getElementById("EducationFeeDropDown");
                        currentElement.innerHTML = "<option>Choose an option</option>";
                        for (var elementNumber in myObject) {
                            console.log(elementNumber);
                            console.log(myObject[elementNumber]);
                            var newOption = document.createElement("option");
                            var newOptionText = document.createTextNode(myObject[elementNumber].text);
                            newOption.appendChild(newOptionText);
                            currentElement.appendChild(newOption);
                        }
                        @if(Model.EducationFee == "Free")
                        {
                            @: currentElement.selectedIndex = 1;
                        }
                        else
                        {
                            @: currentElement.selectedIndex = 2;
                        }
                        var facultyDropDown = document.getElementById("FacultyDropDown");
                        while (facultyDropDown.firstChild) {
                            facultyDropDown.removeChild(facultyDropDown.firstChild);
                        }
                        facultyDropDown.innerHTML = "<option>Choose an option</option>";
                        var currentElement = document.getElementById("EducationFeeDropDown");
                        for (var elementNumber in myObject) {
                            var educationFeeName = myObject[elementNumber].text;
                            if (currentElement.options[currentElement.selectedIndex].text == educationFeeName) {
                                for (var facultyNumber in myObject[elementNumber].children) {
                                    var newOption = document.createElement("option");
                                    var newOptionText = document.createTextNode(myObject[elementNumber].
                                        children[facultyNumber].text);
                                    newOption.appendChild(newOptionText);
                                    facultyDropDown.appendChild(newOption);
                                }
                                break;
                            }
                        }
                    });
            });;

            var specialityDropDown = document.getElementById("SpecialityDropDown");
            specialityDropDown.innerHTML += "<option>@Model.SpecialityName</option>";
            specialityDropDown.selectedIndex = 1;
        }
    </script>
</head>
<body onload="AddSpecialities(), showFatherInfo(), showMotherInfo(), showPrivelegesDefenition(),
        AddChosenEntrantSpeciality()">

        <div style="margin-left:32px; margin-right:32px; text-align:justify">
            @using (Html.BeginForm("EditEntrantInformation", "Entrants", Model))
    {
        @Html.ValidationSummary()
        <div style="text-align:center">
            <h2 style="margin-top:20px">Personal Information</h2>
        </div>
        <div class="form-group">
            <p>
                Name:
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            </p>
            <p>
                Second Name:
                @Html.TextBoxFor(x => x.SecondName, new { @class = "form-control" })
            </p>
            <p>
                Surname:
                @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
            </p>
            <p>
                Date of The Birth:
                @Html.TextBoxFor(x => x.DateOfTheBirth, "{0:d.MM.yyyy}", new { @class = "form-control" })
            </p>
            <p>
                Home Address:
                @Html.TextBoxFor(x => x.HomeAddress, new { @class = "form-control" })
            </p>
            <p>
                Mobile Phone:
                @Html.TextBoxFor(x => x.MobilePhone, new { @class = "form-control" })
            </p>
        </div>

        <div class="text-center">
            <h2>Educational Information</h2>
        </div>

        <div class="form-group">
            <p>
                Chosen Speciality:
                <div id="specialityComboboxesDropDowns" style="display:flex; justify-content:space-between">
                    @Html.DropDownListFor(x => x.EducationFee, Enumerable.Empty<SelectListItem>(), "Choose an option",
new { @id = "EducationFeeDropDown", @style = "width:33%" })
                    <select id="FacultyDropDown" style="width:33%">
                        <option>Choose an option</option>
                    </select>
                    @Html.DropDownListFor(x => x.SpecialityName, Enumerable.Empty<SelectListItem>(), "Choose an option",
    new { @id = "SpecialityDropDown", @style = "width:33%" })
                </div>
            </p>
            <div style="float:left; width:50%; padding-right:10px">
                <p>Finished School Name: @Html.TextBoxFor(x => x.School, new { @class = "form-control" })</p>
                <p>Year of Finishing The School: @Html.TextBoxFor(x => x.YearOfFinishingTheSchool, new { @class = "form-control" })</p>
                <p>Learned Foreign Language: @Html.TextBoxFor(x => x.ForeignLanguage, new { @class = "form-control" })</p>
                <p>
                    Do you need a dormitory: @Html.DropDownListFor(x => x.NeedsDormitory, new[] {
new SelectListItem() {Text = "Yes", Value = bool.TrueString}, new SelectListItem(){Text="No", Value = bool.FalseString} },
"Choose an option", new { @class = "form-control" })
                </p>
            </div>
            <div style="float:right; width:50%; padding-left:10px">
                <p>The Average School Score: @Html.TextBoxFor(x => x.AverageSchoolScore, new { @class = "form-control" }) </p>
            </div>
            <div style="clear:both">

            </div>
        </div>


        <div class="text-center">
            <h2>Privileges</h2>
        </div>
        <div class="form-group">
            <p>
                Do you have privileges: @Html.DropDownListFor(x => x.HasPrivileges, new[] {
new SelectListItem() {Text = "Yes", Value = bool.TrueString}, new SelectListItem(){Text="No", Value = bool.FalseString} },
"Choose an option", new { @class = "form-control", @id = "privilegesDropDown", @onchange = "showPrivelegesDefenition()" })
            </p>
            <p id="privilegesDefenition" style="display:none">
                Defenition of the Privileges: @Html.TextBoxFor(x => x.Privileges, new { @class = "form-control" })
            </p>
        </div>

        <div>
            <div style="float:left; width:50%; padding-right:10px">
                <div class="text-center">
                    <h2>Entrant's Mother Information</h2>
                </div>

                <div class="form-group">
                    <p>
                        Mother: @Html.DropDownListFor(x => x.HasMother, new[] {
new SelectListItem() {Text = "Have got", Value = bool.TrueString}, new SelectListItem(){Text="Haven't got", Value = bool.FalseString} },
"Choose an option", new { @class = "form-control", @id = "motherDropDown", @onchange = "showMotherInfo()" })
                    </p>
                    <div id="motherInfo" style="display:none">
                        <p>Name: @Html.TextBoxFor(x => x.MotherName, new { @class = "form-control" }) </p>
                        <p>Second Name: @Html.TextBoxFor(x => x.MotherSecondName, new { @class = "form-control" })</p>
                        <p>Surname: @Html.TextBoxFor(x => x.MotherSurname, new { @class = "form-control" })</p>
                        <p>Date of The Birth: @Html.TextBoxFor(x => x.MotherDateOfTheBirth, "{0:d.MM.yyyy}",
                                             new { @class = "form-control" }) </p>
                        <p>Home Address: @Html.TextBoxFor(x => x.MotherHomeAddress, new { @class = "form-control" })</p>
                        <p>Mobile Phone: @Html.TextBoxFor(x => x.MotherMobilePhone, new { @class = "form-control" })</p>
                        <p>Place of Work: @Html.TextBoxFor(x => x.MotherPlaceOfWork, new { @class = "form-control" })</p>
                    </div>
                </div>
            </div>

            <div style="float:right; width:50%; padding-left:10px">
                <div class="text-center">
                    <h2>Entrant's Father Information</h2>
                </div>
                <div class="form-group">
                    <p>
                        Father: @Html.DropDownListFor(x => x.HasFather, new[] {
new SelectListItem() {Text = "Have got", Value = bool.TrueString}, new SelectListItem(){Text="Haven't got", Value = bool.FalseString} },
"Choose an option", new { @class = "form-control", @id = "fatherDropDown", @onchange = "showFatherInfo()" })
                    </p>
                    <div id="fatherInfo" style="display:none">
                        <p>Name: @Html.TextBoxFor(x => x.FatherName, new { @class = "form-control" }) </p>
                        <p>Second Name: @Html.TextBoxFor(x => x.FatherSecondName, new { @class = "form-control" })</p>
                        <p>Surname: @Html.TextBoxFor(x => x.FatherSurname, new { @class = "form-control" })</p>
                        <p>Date of The Birth: @Html.TextBoxFor(x => x.FatherDateOfTheBirth, "{0:d.MM.yyyy}",
                                             new { @class = "form-control" }) </p>
                        <p>Home Address: @Html.TextBoxFor(x => x.FatherHomeAddress, new { @class = "form-control" })</p>
                        <p>Mobile Phone: @Html.TextBoxFor(x => x.FatherMobilePhone, new { @class = "form-control" })</p>
                        <p>Place of Work: @Html.TextBoxFor(x => x.FatherPlaceOfWork, new { @class = "form-control" })</p>
                    </div>
                </div>
            </div>
            <div style="clear:both"></div>
        </div>
        <div style="text-align:center">
            <input class="btn-success" type="submit" value="Submit" />
        </div>
       
}
        </div>
</body>

EntrantsApplication/EntrantsApplication.WebUI/Views/Entrants/EdittingEntrantInformation.cshtml
@model EntrantsApplication.Domain.Entities.Entrant

@{
    ViewBag.Title = "Editting Entrant Information";
}

<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
</head>

<body>
    <div class="text-center">
        <h2>The entrant by the name of @Model.Name @Model.SecondName @Model.Surname was successfully edited.</h2>
        @Html.ActionLink("Go back to Main Menu", "MainMenu")
        <p>
            @Html.ActionLink("Go back to the List", "List")
        </p>
    </div>
</body>

EntrantsApplication/EntrantsApplication.WebUI/Views/Entrants/FullEntrantInformation.cshtml
@model EntrantsApplication.Domain.Entities.Entrant

@{
    ViewBag.Title = "Full Entrant Information";
}

<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
</head>

<body>
    <div class="panel-body">
        <div class="text-center" style="display: flex; flex-direction: column; align-items: center;">
            <h1>
                @Html.DisplayFor(modelItem => Model.Name)
                @Html.DisplayFor(modelItem => Model.SecondName)
                @Html.DisplayFor(modelItem => Model.Surname)
                Full Information
            </h1>
            <div class="form-container" style="width: 220px; display: flex; justify-content: space-around;">

                @using (Html.BeginForm("EditEntrant", "Entrants", new { entrantId = Model.EntrantId }))
            {
                @Html.HiddenFor(modelItem => Model.EntrantId)
                <input style="margin-right:20px" type="submit" class="btn-success" value="Edit" />
        }
                @using (Html.BeginForm("DeleteEntrant", "Entrants", new { entrantId = Model.EntrantId }))
            {
                @Html.HiddenFor(modelItem => Model.EntrantId)
                <input type="submit" class="btn-success" value="Delete" />
        }
            </div>

        </div>



        <h3>Personal Information</h3>
        <div class="info-table">
            <table class="table table-bordered">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Second Name
                    </th>
                    <th>
                        Surname
                    </th>
                    <th>
                        Date of The Birth
                    </th>
                    <th>
                        Mobile Phone
                    </th>
                </tr>

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.SecondName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.DateOfTheBirth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.MobilePhone)
                    </td>
                </tr>
            </table>
            <table class="table table-bordered">
                <tr>
                    <th>
                        Home Address
                    </th>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.HomeAddress)
                    </td>
                </tr>
            </table>
        </div>

        <h3>Educational Information</h3>
        <div class="info-table">
            <table class="table table-bordered">
                <tr>
                    <th>
                        Speciality
                    </th>
                    <th>
                        School Name
                    </th>
                    <th>
                        Year of Finishing the School
                    </th>
                    <th>
                        The Average School Score
                    </th>
                    <th>
                        Foreign Language
                    </th>
                    <th>
                        The Need of Dormitory
                    </th>
                </tr>

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.SpecialityName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.School)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.YearOfFinishingTheSchool)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.AverageSchoolScore)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.ForeignLanguage)
                    </td>
                    <td>
                        @if (Model.NeedsDormitory)
                    {
                        @:In Need
                }
                else
                {
                    @:No Need
}
                    </td>
                </tr>

            </table>
        </div>
        @if (Model.HasPrivileges)
    {
        <p></p>
        <h3>Privileges</h3>
        <div style="margin-left:25%; font-size:medium">
            @Html.DisplayFor(modelItem => Model.Privileges)
        </div>
}

        @if (Model.HasMother)
    {
        <h3>Entrant's Mother Information</h3>
        <div class="info-table">
            <table class="table table-bordered">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Second Name
                    </th>
                    <th>
                        Surname
                    </th>
                    <th>
                        The Date of The Birth
                    </th>
                    <th>
                        Mobile Phone
                    </th>
                    <th>
                        Place of Work
                    </th>
                </tr>

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.MotherName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.MotherSecondName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.MotherSurname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.MotherDateOfTheBirth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.MotherMobilePhone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.MotherPlaceOfWork)
                    </td>
                </tr>

            </table>
            <table class="table table-bordered">
                <tr>
                    <th>
                        Home Address
                    </th>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.MotherHomeAddress)
                    </td>
                </tr>
            </table>
        </div>
}

        @if (Model.HasFather)
    {
        <h3>Entrant's Father Information</h3>
        <div class="info-table">
            <table class="table table-bordered">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Second Name
                    </th>
                    <th>
                        Surname
                    </th>
                    <th>
                        The Date of The Birth
                    </th>
                    <th>
                        Mobile Phone
                    </th>
                    <th>
                        Place of Work
                    </th>
                </tr>

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.FatherName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.FatherSecondName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.FatherSurname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.FatherDateOfTheBirth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.FatherMobilePhone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.FatherPlaceOfWork)
                    </td>
                </tr>

            </table>
            <table class="table table-bordered">
                <tr>
                    <th>
                        Home Address
                    </th>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.FatherHomeAddress)
                    </td>
                </tr>
            </table>
        </div>
            }
        </div>
</body>